[package]
name = "weensyos"
version = "0.1.0"
authors = ["Anton Melnychuk <anton.melnychuk@yale.edu>"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
weensyos-shared = { path = "../../shared/rust" }

[profile.dev]
panic = "abort"
overflow-checks = false
opt-level = 0
debug = true

[profile.release]
panic = "abort"
overflow-checks = false
opt-level = 0
codegen-units = 1
